apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: httpbin
  namespace: flux-system
spec:
  releaseName: httpbin
  targetNamespace: test
  interval: 5m
  chart:
    spec:
      chart: httpbin
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
